# Composite Materials
Code for calculation Stiffness matrix: A, B and D of a laminate

Autores: jartero, jpernas


In [1]:
from sympy import integrate, erf, exp, sin, log, oo, pi, sinh, symbols, cos
import numpy as np

Propiedades eláticas del laminado

In [12]:
E11=127e9
E22=9.25e9
# Activate for woven example
#E22=127e9
G12=4.83e9
nu21=0.32
nu12=nu21*E22/E11
# Dilatation coefficients
alpha11=7.47E-06
alpha22=2.86E-05
alpha12=0
# ply thickness
hi=0.19e-3
a=1-nu12*nu21

Stiffness matrix of ply as a function of angle

In [13]:
Q_0=np.array([[E11/a,nu21*E22/a,0],[nu21*E22/a,E22/a,0],[0,0,G12]])
print(Q_0)
# 90 angle
theta=90.0
m=np.cos(theta/180.0*np.pi)
n=np.sin(theta/180.0*np.pi)
T=np.array([[m**2,n**2,2*m*n],[n**2,m**2,-2*m*n],[-m*n,m*n,(m**2-n**2)]])
R=np.array([[1,0,0],[0,1,0],[0,0,0.5]])
Q_theta=np.mat(np.linalg.inv((T)))*np.mat(Q_0)*np.mat(np.linalg.inv((R)))*np.mat(T)*np.mat(R)
Q_90=Q_theta
#print Q_90
## 45 angle
theta=45.0
m=np.cos(theta/180.0*np.pi)
n=np.sin(theta/180.0*np.pi)
T=np.array([[m**2,n**2,2*m*n],[n**2,m**2,-2*m*n],[-m*n,m*n,(m**2-n**2)]])
R=np.array([[1,0,0],[0,1,0],[0,0,0.5]])
Q_theta=np.mat(np.linalg.inv((T)))*np.mat(Q_0)*np.mat(np.linalg.inv((R)))*np.mat(T)*np.mat(R)
Q_45=Q_theta
print(Q_45)
## -45 angle
theta=-45.0
m=np.cos(theta/180.0*np.pi)
n=np.sin(theta/180.0*np.pi)
T=np.array([[m**2,n**2,2*m*n],[n**2,m**2,-2*m*n],[-m*n,m*n,(m**2-n**2)]])
R=np.array([[1,0,0],[0,1,0],[0,0,0.5]])
Q_theta=np.mat(np.linalg.inv((T)))*np.mat(Q_0)*np.mat(np.linalg.inv((R)))*np.mat(T)*np.mat(R)
Q_n45=Q_theta
print(Q_n45)

[[1.27954318e+11 2.98224236e+09 0.00000000e+00]
 [2.98224236e+09 9.31950738e+09 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.83000000e+09]]
[[4.06395774e+10 3.09795774e+10 2.96587025e+10]
 [3.09795774e+10 4.06395774e+10 2.96587025e+10]
 [2.96587025e+10 2.96587025e+10 3.28273351e+10]]
[[ 4.06395774e+10  3.09795774e+10 -2.96587025e+10]
 [ 3.09795774e+10  4.06395774e+10 -2.96587025e+10]
 [-2.96587025e+10 -2.96587025e+10  3.28273351e+10]]


Laminate ply sequence

In [14]:
###########################################################
sec=np.array([45,-45,0,90,90,0,0,90,90,0,-45,45])
#sec=np.array([45,-45,90,0,90,-45,45,90,0,90,45,-45,90,90,-45,45,45,-45,90,90,-45,45,90,0,90,45,-45,90,0,90,-45,45])

In [15]:
plies=len(sec)
# print(sec[1])
print(sec)
i = 0
A = 0
while (i < plies):
	if sec[i] == 0:
		A= A + hi*Q_0
	elif sec[i] == 90:
		A = A +hi*Q_90
	elif sec[i] == 45:
		A = A +hi*Q_45
	elif sec[i] == -45:
		A = A +hi*Q_n45
	i+=1
print(A)
i = 0
D = 0
while (i < plies):
	if sec[i] == 0:
		D= D + 1.0/3.0*Q_0*((plies/2.0-i)**3-(plies/2.0-i-1)**3)*hi**3
	elif sec[i] == 90:
		D= D + 1.0/3.0*Q_90*((plies/2.0-i)**3-(plies/2.0-i-1)**3)*hi**3
	elif sec[i] == 45:
		D= D + 1.0/3.0*Q_45*((plies/2.0-i)**3-(plies/2.0-i-1)**3)*hi**3
	elif sec[i] == -45:
		D= D + 1.0/3.0*Q_n45*((plies/2.0-i)**3-(plies/2.0-i-1)**3)*hi**3
	i+=1
print(D)
#print(D[0,1])
eta=(D[0,1]+2*D[2,2])/((D[0,0]*D[1,1])**0.5)
D_estrella=(((eta+1)/2.0)*(D[0,0]*D[1,1]))**0.5
print(D_estrella)

B = 0
i = 0
while (i < plies):
	if sec[i] == 0:
		B= B + 1.0/2.0*Q_0*((plies/2.0-i)**2-(plies/2.0-i-1)**2)*hi**2
	elif sec[i] == 90:
		B= B + 1.0/2.0*Q_90*((plies/2.0-i)**2-(plies/2.0-i-1)**2)*hi**2
	elif sec[i] == 45:
		B= B + 1.0/2.0*Q_45*((plies/2.0-i)**2-(plies/2.0-i-1)**2)*hi**2
	elif sec[i] == -45:
		B= B + 1.0/2.0*Q_n45*((plies/2.0-i)**2-(plies/2.0-i-1)**2)*hi**2
	i+=1
print(B)

[ 45 -45   0  90  90   0   0  90  90   0 -45  45]
[[1.35214186e+08 2.80774872e+07 0.00000000e+00]
 [2.80774872e+07 1.35214186e+08 5.58793545e-09]
 [0.00000000e+00 5.58793545e-09 3.22903746e+07]]
[[51.58785147 22.40496593  4.06858081]
 [22.40496593 45.07812217  4.06858081]
 [ 4.06858081  4.06858081 24.22998875]]
53.58555100517861
[[6.36646291e-12 9.09494702e-13 0.00000000e+00]
 [9.09494702e-13 2.72848411e-12 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00]]


![](Effect-of-stiffness-matrix-elements-on-deformation-of-the-laminate-element.png)